services:
  - type: web
    name: ml-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 120 -w 1 -b 0.0.0.0:8080 app:app"
    envVars:
      - key: PORT
        value: 10000
